---
title: "רשימת מקורות"
---

1.  **״ארכיאולוגיה מהחלל״: חישה מרחוק וארכיאולוגיה**

\*Ur, Jason 2017. ‘Physical and Cultural Landscapes of Assyria’. In Frahm, E. (ed.). *A Companion to Assyria*. Wiley-Blackwell: 13-35.

\*Jotheri, Jaafar and Allen, Mark B. (2020) Recognition of ancient channels and archaeological sites in the Mesopotamian floodplain using satellite imagery and digital topography. In *New agendas in remote sensing and landscape archaeology in the Near East : studies in honour of Tony J. Wilkinson*. Oxford: Archaeopress, pp. 283-305.

Radner, K. 2015. *Ancient Assyria: A Very Short Introduction*. Oxford. Pp. 1-44.

2.  **המאה ה-9 לפנה"ס וההתפשטות האשורית מערבה**

\*Bonacossi, Daniele Morandi. 2018. ‘The Creation of the Assyrian Heartland: New Data from the “Land behind Nineveh”’. In *The Archaeology of Imperial Landscapes*, edited by Bleda S. Düring and Tesse D. Stek, 1st ed., 48–85. Cambridge University Press.

Liverani, M. 2004. “Assyria in the Ninth Century: Continuity or Change?”. In G. Frame (ed.), *with the assistance of Linda S. Wilding, From the Upper Sea to the Lower Sea. Studies on the History of Assyria and Babylonia in Honour of A.K. Grayson* (PIHANS 101). Leiden, 213–226.

3.  **הארמים והלווים: עלייתם והתהוותם הפוליטית-טריטוריאלית**

\*Sader, H. 2014. “History”. In: H. Niehr (ed.) *The Aramaeans in Ancient Syria* (Handbuch der Orientalistik 106). Leiden: Brill, 11–36.

\*Osborne, James F. 2017. Exploring the lower settlements of Iron Age capitals in Anatolia and Syria. *Antiquity* *91*(355), 90-107. <doi:10.15184/aqy.2016.254>.

Massa, M., Bachhuber, C., Şahin, F., Erpehlivan, H., Osborne, J., & Lauricella, A. 2020. A landscape-oriented approach to urbanisation and early state formation on the Konya and Karaman plains, Turkey. *Anatolian Studies* 70, 45-75. <doi:10.1017/S0066154620000034>

Matessi, Alvise, Emre Dalkiliç, and Lorenzo D’Alfonso. 2018. “Settlement Patterns, Ancient Routes and Environmental Change in South Cappadocia (Turkey), During The Holocene.” Ömer Halisdemir Üniversitesi Mühendislik Bilimleri Dergisi, 1107–12. <https://doi.org/10.28948/ngumuh.502278>.

י' איקדה, ממלכת חמת ויחסיה המדיניים עם ארם וישראל. עבודת דוקטור, האוניברסיטה העברית בירושלים, תשל"ז.

4.  **ממלכות הארמים והלווים: סקירה ארכיאולוגית והיסטורית**

**\***א' זינגר, "פרק 12: הממלכות הניאו-חתיות", "פרק 13: בני חת במקרא", בתוך: *החתים ותרבותם* (ספריית האינציקלופדיה המקראית 26). ירושלים, תשס"ט, 108-104.

י' דגן וש' דר, *מדריך הסיור לדרום מזרח תורכיה: הכינוס הס' לידיעת הארץ והארצות השכנות (25-17 באוקטובר, 2005)*. ירושלים, תשס"ה.

﻿\*Osborne, James F. 2014. Settlement Planning and Urban Symbology in Syro-Anatolian Cities. *Cambridge Archaeological Journal* 24, 195-214. <doi:10.1017/S0959774314000444>

Niehr, Herbert, ed. 2014. *The Aramaeans in Ancient Syria*. Handbuch Der Orientalistik 106. Leiden: Brill.

Lipiński, E. 2000. *The Aramaeans. Their Ancient History, Culture. Religion* (Orientalia Lovaniensia Analecta 100). Leuven.

Bryce, T. 2012. *The World of the Neo-Hittite Kingdoms: A Political and Military History*. Oxford: Oxford University Press.\
Hawkins, J. D. 2000. *Corpus of Hieroglyphic Luwian Inscriptions I. Inscriptions of the Iron Age*. Berlin.\
Melchert, H. C. (ed.) 2003. *The Luwians*. Leiden.

5.  **הצבא האשורי: מבנה, אסטרטגיה ותורת לחימה**

\*ח' תדמור, "מסעות המלחמה האשוריים לפלשת", בתוך מ' כוגן אשור, בבל ויהודה: מחקרים בתולדות המזרח הקדום. ירושלים, תשס"ו, 254-229.

ע' בוסתנאי, "מדיניות ההגליה של האימפריות אשור ובבל", בתוך ע' בוסתנאי, *גלות ישראל ויהודה באשור ובבבל*, חיפה, תש"ע, 99-124.

\*Radner, K. and Marriott, J. 2015. “Sustaining the Assyrian army among friends and enemies in 714 BCE”. *Journal of Cuneiform Studies* 67: 127–143.

Nadali, D. 2010. “Assyrian Open Field Battles. An Attempt at Reconstruction and Analysis”. In: J. Vidal (ed.) *Studies on War in the Ancient Near East. Collected Essays on Military History* (Altes Orient und Altes Testament 372). Münster, 117–150.

6.  **הבירות האשוריות ופיתוח אזורי ליבה: מפעלי בניה ושינוע אוכלוסייה**

\*Ur, Jason and Julian Reade. 2015. The Hydraulic Landscape of Nimrud. *Mesopotamia* 50: 25-51.

Bonacossi, Daniele Morandi. 2018. ‘Water for Nineveh. The Nineveh Irrigation System in the Regional Context of the ‘Assyrian Triangle’: A first Geoarchaeological Assessment’. In *Water for Assyria*, edited by Hartmut Kühne. Wiesbaden, 77–116.

7.  **כלכלה ויחסי מסחר בין אשור למערב**

\*מ' אילת, "המסחר הבינלאומי בארץ ישראל תחת שלטון אשור." *פרקים בתולדות המסחר בארץ ישראל* (1990) 88-67.

י' אפעל, "משמעותו של השלטון האימפריאלי האשורי על פי תעודות לא-ספרותיות הנוגעות ל"עבר הנהר"", *באר-שבע* יט (2010) 69-31.

\*Aster, S. Z. & Faust, A. 2018. *The Southern Levant under Assyrian Domination*. Eisenbrauns. **Selected chapter**

Bagg, A. 2013. “Palestine under Assyrian Rule: A New Look at the Assyrian Imperial Policy in the West,” *Journal of American Oriental Society* 133: 119–144.

8.  **מבט על והתפוררות האימפריה האשורית ברקורד הארכיאולוגי**

\*Frahm, E. Assyria's Downfall and the "Afterlife" and Legacy of the Assyrian Empire (631-609). In Frahm, E. (ed.). 2017. *A Companion to Assyria*. Wiley-Blackwell: 191-208.

﻿Radner, K. 2017. Assur’s "Second Temple Period": The Restoration of the Cult of Aššur, c. 538 BCE. In C. Levin and R. Müller (eds.) *Herrschaftslegitmation in vorderorientalischen Reichen der Eisenzeit*. Tübingen: Mohr Siebeck, pp. 77–96.
